#!/usr/bin/env python
"""
File: lib.py
Package: grindstone
Author: Elijah Caine
Description:
    Grindstone is a small package to keep track of your to-do items.
"""
from grindstone import lib

if __name__ == '__main__':
    print('Grindstone')
